name: firstworkflow
on:
  push: 
    branches: ["master"]
  workflow_dispatch:
jobs:
  checkout: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: print
        run: |
          echo "$(who am i)"
          echo "$(hostname)"