name: firstworkflow
on: workflow_dispatch
jobs:
  checkout: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: print
        run: |
          echo "User Name: $(whoami) \n"
          echo "\n "
          echo "Host Name: $(hostname) \n"
          