name: output context
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      jobstatus: ${{ toJSON(job) }}
    steps:
      - name: Run a multi-line script
        run: |
          echo " ${{ toJSON(github) }}"
          echo "Job Status: ${{ toJSON(job) }}"
          
  jobstat:
    runs-on: ubuntu-latest
    needs: info
    steps:
      - name: previousjobstat
        run: |
          echo "  Previous Job status: ${{ needs.info.outputs.jobstatus }}"
